### ISSUE TITLE
How to upload the generated release zip file?

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/plugin-template#5]
**Describe the bug**
The github action generates a new release zip file, how should I use this file?

When I download the file from "Releases" I get a zip with files directly saved in the root, however the "upload plugin" button in the admin page need a zip file with a folder:
```python
        # there should be a method to check for plugin integrity
        if len(extracted_contents) != 1:
            raise Exception("A plugin should consist in one new folder: "
                            "found many contents in compressed archive or plugin already present.")
```

**Workaround**
Uncompress the zip file, create a folder with the name of the plugin, add the plugins file to the new folder, zip this new folder, upload the new zip file

**Expected behavior**
The zip file can be uploaded with the button "upload plugin"

**Comment by nicola-corbellini** [comment]
The zip is meant to be used by the plugin registry once it will be online.
If you are creating your own plugin using this template you should just clone it inside `core/cat/plugins`.

**Comment by sambarza** [comment]
I miss the plugin registry, waiting for it ;-)
